// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:h3xboard/services/rust/frb_generated.dart';

/// Whether this build can actually run a program. Dart asks before offering Run.
bool pythonIsSupported() => RustLib.instance.api.crateApiPythonPythonIsSupported();

/// Hands over `python.wasm` and the standard library zip, once.
///
/// Together they are about 20 MB, so they cross the bridge on first use and are
/// held afterwards; the interpreter is translated once and reused. Calling again
/// is cheap and does nothing.
Future<void> pythonLoad({required List<int> wasm, required List<int> stdlib}) =>
    RustLib.instance.api.crateApiPythonPythonLoad(wasm: wasm, stdlib: stdlib);

/// Runs `code` to completion, feeding `stdin` to `input()`.
///
/// Never fails for a *program* error — a traceback comes back in
/// [`PythonOutcome::stderr`] with a non-zero exit code, because a pupil's
/// mistake is a normal outcome here, not an exception. `Err` means the runtime
/// itself could not start.
Future<PythonOutcome> pythonRun({required String code, required String stdin}) =>
    RustLib.instance.api.crateApiPythonPythonRun(code: code, stdin: stdin);

/// Asks a running program to stop.
///
/// Synchronous and lock-free on purpose: it has to be answerable while
/// [`python_run`] is still in flight, so it must not queue behind it.
void pythonCancel() => RustLib.instance.api.crateApiPythonPythonCancel();

/// What one run of a program produced. Mirrors Dart's `PythonResult`.
class PythonOutcome {
  final String stdout;
  final String stderr;

  /// 0 when the program finished normally, 130 when Stop was pressed.
  final int exitCode;

  /// Output hit the per-stream cap and was cut short.
  final bool truncated;
  final BigInt durationMs;

  const PythonOutcome({
    required this.stdout,
    required this.stderr,
    required this.exitCode,
    required this.truncated,
    required this.durationMs,
  });

  @override
  int get hashCode => stdout.hashCode ^ stderr.hashCode ^ exitCode.hashCode ^ truncated.hashCode ^ durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PythonOutcome &&
          runtimeType == other.runtimeType &&
          stdout == other.stdout &&
          stderr == other.stderr &&
          exitCode == other.exitCode &&
          truncated == other.truncated &&
          durationMs == other.durationMs;
}
