import 'dart:convert';

import 'package:flutter/services.dart';

/// Access to the bundled Noto Emoji artwork and its searchable metadata.
///
/// Everything here is generated by `just gen-emoji` into assets/emoji/ — see
/// tool/generate_emoji_assets.dart for the pipeline and the pinned upstream
/// versions. Emoji are drawn from compiled vector graphics rather than a color
/// font because Flutter's Impeller renderer draws neither CBDT bitmap tables nor
/// COLRv1 vector tables, so a bundled emoji font renders as nothing at all.

/// Code point for the emoji variation selector (VS16), which Noto's file names
/// leave out.
const int _variationSelector = 0xFE0F;

/// The asset path holding [emoji]'s artwork.
///
/// Derived from the characters themselves rather than looked up, so rendering an
/// emoji widget costs nothing at startup — only the picker loads the index.
String emojiAssetPath(String emoji) => 'assets/emoji/vec/${emojiAssetKey(emoji)}.vec';

/// The artwork file name for [emoji]: code points minus variation selectors,
/// lowercase hex padded to at least four digits, underscore-joined.
///
/// Must stay byte-identical to `EmojiEntry.formatAssetKey` in
/// tool/generate_emoji_assets.dart, which names the files this looks up.
String emojiAssetKey(String emoji) => emoji.runes
    .where((cp) => cp != _variationSelector)
    .map((cp) => cp.toRadixString(16).padLeft(4, '0'))
    .join('_');

/// A Fitzpatrick skin tone, or [none] for the default yellow artwork.
///
/// The order of the toned values matches the order the generator writes tone
/// variants in, so [EmojiEntry.withTone] can index straight into them.
enum EmojiSkinTone {

  none,
  light,
  mediumLight,
  medium,
  mediumDark,
  dark;

  /// Restores a tone from its persisted name, falling back to [none].
  static EmojiSkinTone fromWire(Object? value) =>
      EmojiSkinTone.values.firstWhere((t) => t.name == value, orElse: () => EmojiSkinTone.none);

  /// The emoji that represents this tone in the tone selector — the "hand" emoji
  /// in that tone, matching what every other emoji keyboard shows.
  String get sample => switch (this) {
        EmojiSkinTone.none => '\u{270B}',
        EmojiSkinTone.light => '\u{270B}\u{1F3FB}',
        EmojiSkinTone.mediumLight => '\u{270B}\u{1F3FC}',
        EmojiSkinTone.medium => '\u{270B}\u{1F3FD}',
        EmojiSkinTone.mediumDark => '\u{270B}\u{1F3FE}',
        EmojiSkinTone.dark => '\u{270B}\u{1F3FF}',
      };

}

/// The nine pickable Unicode emoji groups, in Unicode's own order.
///
/// Unicode's tenth group ("Component") is deliberately absent: it holds bare
/// skin-tone and hair modifiers, which are never pickable on their own.
enum EmojiGroupId {

  smileysEmotion,
  peopleBody,
  animalsNature,
  foodDrink,
  travelPlaces,
  activities,
  objects,
  symbols,
  flags;

  static EmojiGroupId? fromWire(String value) =>
      EmojiGroupId.values.where((g) => g.name == value).firstOrNull;

}

/// One pickable emoji: its base characters, its skin-tone variants (empty when
/// it has none), and the localized text it can be searched by.
class EmojiEntry {

  /// The default, untoned characters — what gets stored when no tone is picked.
  final String emoji;

  /// The five toned variants in [EmojiSkinTone] order, or empty when this emoji
  /// takes no skin tone. Populated only when all five have artwork.
  final List<String> tones;

  /// The CLDR display name in the catalog's locale, e.g. "thumbs up".
  final String name;

  /// Lowercased name and CLDR keywords, joined by `|`, ready for [EmojiCatalog.search].
  final String _searchText;

  EmojiEntry({
    required this.emoji,
    required this.tones,
    required this.name,
    required String keywords,
  }) : _searchText = '${name.toLowerCase()}|${keywords.toLowerCase()}';

  bool get supportsSkinTones => tones.isNotEmpty;

  /// This emoji in [tone], or its untoned form when it takes no skin tone.
  String withTone(EmojiSkinTone tone) {
    if (tone == EmojiSkinTone.none || tones.isEmpty) return emoji;
    return tones[tone.index - 1];
  }

}

/// One picker category and the emoji it holds, in Unicode order.
class EmojiGroup {

  final EmojiGroupId id;
  final List<EmojiEntry> emoji;

  /// Whether any emoji here takes a skin tone, and therefore whether this group
  /// has toned artwork packs at all. Most groups have none, and asking for a
  /// pack that was never written costs a 404 per category.
  final bool hasSkinTones;

  EmojiGroup({required this.id, required this.emoji})
      : hasSkinTones = emoji.any((e) => e.supportsSkinTones);

}

/// The full emoji catalog for one locale: every group in Unicode order, plus
/// localized search.
///
/// Loaded lazily on first use and cached per locale, so the ~1900 entries and
/// their keywords are only parsed when the picker is actually opened.
class EmojiCatalog {

  static const _indexAsset = 'assets/emoji/index.json';

  /// Locales with a generated labels file. Anything else falls back to English
  /// names so the picker still works (and still searches) in every language.
  static const _labelLocales = {'en', 'nl'};
  static const _fallbackLocale = 'en';

  static final Map<String, Future<EmojiCatalog>> _cache = {};

  /// The Unicode Emoji release the bundled artwork was generated from, e.g. "17.0".
  final String emojiVersion;

  final List<EmojiGroup> groups;

  const EmojiCatalog({required this.emojiVersion, required this.groups});

  /// The catalog for [languageCode], loading it on first request.
  static Future<EmojiCatalog> load(String languageCode) {
    final locale = _labelLocales.contains(languageCode) ? languageCode : _fallbackLocale;
    return _cache.putIfAbsent(locale, () => _load(locale));
  }

  static Future<EmojiCatalog> _load(String locale) async {
    final index = jsonDecode(await rootBundle.loadString(_indexAsset)) as Map<String, dynamic>;
    final labels =
        jsonDecode(await rootBundle.loadString('assets/emoji/labels_$locale.json')) as Map<String, dynamic>;

    final groups = <EmojiGroup>[];
    for (final rawGroup in index['groups'] as List<dynamic>) {
      final group = rawGroup as Map<String, dynamic>;
      final id = EmojiGroupId.fromWire(group['id'] as String);
      // A group id the app doesn't know is newer data than this build; skipping
      // it keeps the rest of the picker usable.
      if (id == null) continue;

      final entries = <EmojiEntry>[];
      for (final rawEntry in group['emoji'] as List<dynamic>) {
        // Each entry is [base, ...five toned variants] — tones only when present.
        final variants = (rawEntry as List<dynamic>).cast<String>();
        final label = labels[variants.first] as List<dynamic>?;
        entries.add(EmojiEntry(
          emoji: variants.first,
          tones: variants.skip(1).toList(),
          name: label == null ? variants.first : label[0] as String,
          keywords: label == null ? '' : label[1] as String,
        ));
      }
      groups.add(EmojiGroup(id: id, emoji: entries));
    }

    return EmojiCatalog(emojiVersion: index['emojiVersion'] as String, groups: groups);
  }

  /// Emoji matching [query], best match first.
  ///
  /// Matches are ranked so that a name match always outranks a keyword match and
  /// an earlier match outranks a later one — typing "smi" surfaces "smiling face"
  /// ahead of everything that merely lists "smile" as a keyword. Ties keep
  /// Unicode order, which is the order the groups are already in.
  List<EmojiEntry> search(String query) {
    final needle = query.trim().toLowerCase();
    if (needle.isEmpty) return const [];

    final matches = <(int, int, EmojiEntry)>[];
    for (final group in groups) {
      for (final entry in group.emoji) {
        final score = _score(entry, needle);
        // The running position is carried as an explicit tiebreaker: Dart's sort
        // is not stable, so equal scores would otherwise come back in an
        // arbitrary order that changes between runs.
        if (score != null) matches.add((score, matches.length, entry));
      }
    }

    matches.sort((a, b) => a.$1 == b.$1 ? a.$2.compareTo(b.$2) : a.$1.compareTo(b.$1));
    return [for (final match in matches) match.$3];
  }

  /// [entry]'s rank for [needle] (lower is better), or null when it doesn't match.
  static int? _score(EmojiEntry entry, String needle) {
    final name = entry._searchText.split('|').first;
    if (name == needle) return 0;
    if (name.startsWith(needle)) return 1;

    final index = entry._searchText.indexOf(needle);
    if (index < 0) return null;
    // Word-initial matches ("...|grin|...") read as intentional; a match in the
    // middle of a word is weaker, so it sorts last.
    final isWordStart = index == 0 || entry._searchText[index - 1] == '|' || entry._searchText[index - 1] == ' ';
    return isWordStart ? 2 : 3;
  }

}
